"""Adding first name and surname.

Revision ID: 61cfe45007f8
Revises: 78407d9ece35
Create Date: 2020-12-15 13:54:01.485349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cfe45007f8'
down_revision = '78407d9ece35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('user_model', sa.Column('surname', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'surname')
    op.drop_column('user_model', 'first_name')
    # ### end Alembic commands ###
